version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - api
    restart: always

volumes:
  dbdata: null
